# from urdf describing hokuyo specs
kld_err: 0.03
kld_z: 0.97
#laser_min_range: -1.0
laser_max_range: 10

laser_max_beams: 120

min_particles: 150
max_particles: 3000

update_min_d: 0.5 
update_min_a: 0.75

odom_alpha1: 0.0001
odom_alpha2: 0.0001
odom_alpha3: 0.0001
odom_alpha4: 0.0001

laser_z_hit: 0.98
laser_z_rand: 0.02
