# from urdf describing hokuyo specs
kld_err: 0.03
kld_z: 0.97
laser_min_range: 0.1
laser_max_range: 10

laser_max_beams: 10

min_particles: 150
max_particles: 3000

# slightly faster updates seem to work better
update_min_d: 0.25
update_min_a: 0.5

odom_alpha1: 0.001
odom_alpha2: 0.001
odom_alpha3: 0.001
odom_alpha4: 0.001

laser_z_hit: 0.90
laser_z_rand: 0.10
